/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as FootwearIndexImport } from './routes/footwear/index'
import { Route as FootwearIdImport } from './routes/footwear/$id'

// Create/Update Routes

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const FootwearIndexRoute = FootwearIndexImport.update({
  id: '/footwear/',
  path: '/footwear/',
  getParentRoute: () => rootRoute,
} as any)

const FootwearIdRoute = FootwearIdImport.update({
  id: '/footwear/$id',
  path: '/footwear/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/footwear/$id': {
      id: '/footwear/$id'
      path: '/footwear/$id'
      fullPath: '/footwear/$id'
      preLoaderRoute: typeof FootwearIdImport
      parentRoute: typeof rootRoute
    }
    '/footwear/': {
      id: '/footwear/'
      path: '/footwear'
      fullPath: '/footwear'
      preLoaderRoute: typeof FootwearIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/footwear/$id': typeof FootwearIdRoute
  '/footwear': typeof FootwearIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/footwear/$id': typeof FootwearIdRoute
  '/footwear': typeof FootwearIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/footwear/$id': typeof FootwearIdRoute
  '/footwear/': typeof FootwearIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/footwear/$id' | '/footwear'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/footwear/$id' | '/footwear'
  id: '__root__' | '/' | '/about' | '/footwear/$id' | '/footwear/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  FootwearIdRoute: typeof FootwearIdRoute
  FootwearIndexRoute: typeof FootwearIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  FootwearIdRoute: FootwearIdRoute,
  FootwearIndexRoute: FootwearIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/footwear/$id",
        "/footwear/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/footwear/$id": {
      "filePath": "footwear/$id.tsx"
    },
    "/footwear/": {
      "filePath": "footwear/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
